name: CI
on:
  push:
    branches: [NativeNFT]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up jdk 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
      - name: Build Gradle
        run: ./gradlew clean build


