name: Gradle CI
on:
  push:
    branches: [NativeNFT]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build


